python train.py --model DenseNet121
python train.py --model EfficientNet_V2_M
python train.py --model MobileNet_V2
python train.py --model ResNet50
python train.py --model RegNet_Y_32GF
python train.py --model ResNet101
python train.py --model SqueezeNet1_1
python train.py --model VGG16
python train.py --model VGG19
python train.py --model InceptionV3
python train.py --model Swin_V2_B
python train.py --model ViT_B_16
python train.py --model ViT_H_14
python train.py --model EfficientNet_V2_L
python train.py --model EfficientNet_V2_S
