# Step 1: Train all models 
python train.py --model SqueezeNet1_1
python train.py --model DenseNet121
python train.py --model DenseNet161
python train.py --model DenseNet169
python train.py --model EfficientNet_V2_M
python train.py --model MobileNet_V2
python train.py --model ResNet50
python train.py --model RegNet_Y_32GF
python train.py --model ResNet101
python train.py --model VGG11
python train.py --model VGG13
python train.py --model VGG16
python train.py --model VGG19
python train.py --model InceptionV3
python train.py --model Swin_V2_B
python train.py --model ViT_B_16
python train.py --model ViT_H_14
python train.py --model EfficientNet_V2_L
python train.py --model EfficientNet_V2_S
python train.py --model EfficientNet_B7
python train.py --model EfficientNet_B6
python train.py --model ConvNeXt_Base
python train.py --model ConvNeXt_Small
python train.py --model MaxViT_T
python train.py --model MobileNet_V3_Large
python train.py --model RegNet_Y_16GF
python train.py --model RegNet_Y_8GF
python train.py --model ResNet152
python train.py --model ResNet34
python train.py --model ResNet18
python train.py --model ViT_B_32
python train.py --model ViT_L_16
python train.py --model ViT_L_32

# Step 2: prune and KD all models 
python compression.py --model SqueezeNet1_1
python compression.py --model DenseNet121
python compression.py --model DenseNet161
python compression.py --model DenseNet169
python compression.py --model EfficientNet_V2_M
python compression.py --model MobileNet_V2
python compression.py --model ResNet50
python compression.py --model RegNet_Y_32GF
python compression.py --model ResNet101
python compression.py --model VGG11
python compression.py --model VGG13
python compression.py --model VGG16
python compression.py --model VGG19
python compression.py --model InceptionV3
python compression.py --model Swin_V2_B
python compression.py --model ViT_B_16
python compression.py --model ViT_H_14
python compression.py --model EfficientNet_V2_L
python compression.py --model EfficientNet_V2_S
python compression.py --model EfficientNet_B7
python compression.py --model EfficientNet_B6
python compression.py --model ConvNeXt_Base
python compression.py --model ConvNeXt_Small
python compression.py --model MaxViT_T
python compression.py --model MobileNet_V3_Large
python compression.py --model RegNet_Y_16GF
python compression.py --model RegNet_Y_8GF
python compression.py --model ResNet152
python compression.py --model ResNet34
python compression.py --model ResNet18
python compression.py --model ViT_B_32
python compression.py --model ViT_L_16
python compression.py --model ViT_L_32

# Step 3: quantize all models
python quantization.py --model SqueezeNet1_1
python quantization.py --model DenseNet121
python quantization.py --model DenseNet161
python quantization.py --model DenseNet169
python quantization.py --model EfficientNet_V2_M
python quantization.py --model MobileNet_V2
python quantization.py --model ResNet50
python quantization.py --model RegNet_Y_32GF
python quantization.py --model ResNet101
python quantization.py --model VGG11
python quantization.py --model VGG13
python quantization.py --model VGG16
python quantization.py --model VGG19
python quantization.py --model InceptionV3
python quantization.py --model Swin_V2_B
python quantization.py --model ViT_B_16
python quantization.py --model ViT_H_14
python quantization.py --model EfficientNet_V2_L
python quantization.py --model EfficientNet_V2_S
python quantization.py --model EfficientNet_B7
python quantization.py --model EfficientNet_B6
python quantization.py --model ConvNeXt_Base
python quantization.py --model ConvNeXt_Small
python quantization.py --model MaxViT_T
python quantization.py --model MobileNet_V3_Large
python quantization.py --model RegNet_Y_16GF
python quantization.py --model RegNet_Y_8GF
python quantization.py --model ResNet152
python quantization.py --model ResNet34
python quantization.py --model ResNet18
python quantization.py --model ViT_B_32
python quantization.py --model ViT_L_16
python quantization.py --model ViT_L_32
