#python compression.py --model SqueezeNet1_1
#python compression.py --model DenseNet121
#python compression.py --model DenseNet161
#python compression.py --model DenseNet169
#python compression.py --model EfficientNet_V2_M
#python compression.py --model MobileNet_V2
#python compression.py --model ResNet50
#python compression.py --model RegNet_Y_32GF
#python compression.py --model ResNet101
#python compression.py --model VGG11
#python compression.py --model VGG13
#python compression.py --model VGG16
#python compression.py --model VGG19
# python compression.py --model Swin_V2_B
#python compression.py --model ViT_B_32
#python compression.py --model ViT_B_16
# python compression.py --model EfficientNet_V2_L
#python compression.py --model EfficientNet_V2_S
#python compression.py --model EfficientNet_B7
#python compression.py --model EfficientNet_B6
#python compression.py --model ConvNeXt_Base
#python compression.py --model ConvNeXt_Small
#python compression.py --model MobileNet_V3_Large
#python compression.py --model RegNet_Y_16GF
#python compression.py --model RegNet_Y_8GF
#python compression.py --model ResNet152
#python compression.py --model ResNet34
#python compression.py --model ResNet18
#python compression.py --model ViT_L_16
#python compression.py --model ViT_L_32
#python compression.py --model MaxViT_T
#python compression.py --model ViT_H_14
