python quantization.py --model SqueezeNet1_1
python quantization.py --model DenseNet121
python quantization.py --model DenseNet161
python quantization.py --model DenseNet169
python quantization.py --model EfficientNet_V2_M
python quantization.py --model MobileNet_V2
python quantization.py --model ResNet50
python quantization.py --model RegNet_Y_32GF
python quantization.py --model ResNet101
python quantization.py --model VGG11
python quantization.py --model VGG13
python quantization.py --model VGG16
python quantization.py --model VGG19
python quantization.py --model InceptionV3
python quantization.py --model Swin_V2_B
python quantization.py --model ViT_B_16
python quantization.py --model ViT_H_14
python quantization.py --model EfficientNet_V2_L
python quantization.py --model EfficientNet_V2_S
python quantization.py --model EfficientNet_B7
python quantization.py --model EfficientNet_B6
python quantization.py --model ConvNeXt_Base
python quantization.py --model ConvNeXt_Small
python quantization.py --model MaxViT_T
python quantization.py --model MobileNet_V3_Large
python quantization.py --model RegNet_Y_16GF
python quantization.py --model RegNet_Y_8GF
python quantization.py --model ResNet152
python quantization.py --model ResNet34
python quantization.py --model ResNet18
python quantization.py --model ViT_B_32
python quantization.py --model ViT_L_16
python quantization.py --model ViT_L_32
