python train.py --model SqueezeNet1_1
python train.py --model DenseNet121
python train.py --model DenseNet161
python train.py --model DenseNet169
python train.py --model EfficientNet_V2_M
python train.py --model MobileNet_V2
python train.py --model ResNet50
python train.py --model RegNet_Y_32GF
python train.py --model ResNet101
python train.py --model VGG11
python train.py --model VGG13
python train.py --model VGG16
python train.py --model VGG19
python train.py --model InceptionV3
python train.py --model Swin_V2_B
python train.py --model ViT_B_16
python train.py --model ViT_H_14
python train.py --model EfficientNet_V2_L
python train.py --model EfficientNet_V2_S
python train.py --model EfficientNet_B7
python train.py --model EfficientNet_B6
python train.py --model ConvNeXt_Base
python train.py --model ConvNeXt_Small
python train.py --model MaxViT_T
python train.py --model MobileNet_V3_Large
python train.py --model RegNet_Y_16GF
python train.py --model RegNet_Y_8GF
python train.py --model ResNet152
python train.py --model ResNet34
python train.py --model ResNet18
python train.py --model ViT_B_32
python train.py --model ViT_L_16
python train.py --model ViT_L_32
